In [139]:
import tensorflow as tf
import scipy
import matplotlib.pyplot as plt
import numpy as np
sess = tf.Session()


img = tf.placeholder(tf.float32, shape=(None))

digit = plt.imread("book2.jpg")
feed_dict = {img:digit}

print(feed_dict)


{<tf.Tensor 'Placeholder_11:0' shape=<unknown> dtype=float32>: array([[[162, 144, 132],
        [169, 151, 139],
        [175, 157, 145],
        ...,
        [172, 153, 136],
        [170, 151, 134],
        [177, 158, 141]],

       [[180, 162, 148],
        [181, 163, 149],
        [176, 158, 144],
        ...,
        [189, 170, 153],
        [190, 171, 154],
        [198, 179, 162]],

       [[151, 133, 119],
        [157, 139, 125],
        [164, 146, 132],
        ...,
        [182, 163, 146],
        [181, 162, 145],
        [178, 159, 142]],

       ...,

       [[161, 144, 128],
        [159, 142, 126],
        [159, 142, 126],
        ...,
        [173, 150, 134],
        [170, 147, 131],
        [178, 159, 142]],

       [[183, 166, 150],
        [179, 162, 146],
        [177, 160, 144],
        ...,
        [167, 144, 128],
        [164, 141, 125],
        [168, 149, 132]],

       [[164, 147, 131],
        [158, 141, 125],
        [151, 134, 118],
        ...,
        [15

In [140]:
print(type(feed_dict))

<class 'dict'>


In [141]:
print(digit)

[[[162 144 132]
  [169 151 139]
  [175 157 145]
  ...
  [172 153 136]
  [170 151 134]
  [177 158 141]]

 [[180 162 148]
  [181 163 149]
  [176 158 144]
  ...
  [189 170 153]
  [190 171 154]
  [198 179 162]]

 [[151 133 119]
  [157 139 125]
  [164 146 132]
  ...
  [182 163 146]
  [181 162 145]
  [178 159 142]]

 ...

 [[161 144 128]
  [159 142 126]
  [159 142 126]
  ...
  [173 150 134]
  [170 147 131]
  [178 159 142]]

 [[183 166 150]
  [179 162 146]
  [177 160 144]
  ...
  [167 144 128]
  [164 141 125]
  [168 149 132]]

 [[164 147 131]
  [158 141 125]
  [151 134 118]
  ...
  [156 133 117]
  [151 128 112]
  [151 132 115]]]


In [142]:
print(type(digit))

<class 'numpy.ndarray'>


In [143]:
print(digit.shape)
sample = digit.copy()
sample.resize((1, 136, 369, 3))
print(sample.shape)

(136, 369, 3)
(1, 136, 369, 3)


In [144]:
label = [1]

In [145]:
import scipy.misc
scipy.misc.imsave('test.jpg', digit)

/Users/admin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  


In [153]:
test_r = np.zeros((136, 369), dtype=int)
for i in range(136):
    for j in range(369):
        test_r[i, j] = digit[i, j, 0]
scipy.misc.imsave('test_red.jpg', test_r)
        
test_r = test_r[:28,:28]
print(test_r)

test_g = np.zeros((136, 369), dtype=int)
for i in range(136):
    for j in range(369):
        test_g[i, j] = digit[i, j, 1]
scipy.misc.imsave('test_green.jpg', test_g)

        
test_g = test_g[:28,:28]
print(test_g)

test_b = np.zeros((136, 369), dtype=int)
for i in range(136):
    for j in range(369):
        test_b[i, j] = digit[i, j, 2]
scipy.misc.imsave('test_blue.jpg', test_b)
        
test_b = test_b[:28,:28]        
print(test_b)

[[162 169 175 175 172 172 178 185 167 167 165 168 177 184 181 172 158 156
  152 145 142 148 160 170 171 170 170 169]
 [180 181 176 163 147 134 129 130 141 156 157 146 154 176 178 162 153 158
  164 164 162 160 162 165 166 167 168 169]
 [151 157 164 168 170 174 181 186 180 172 168 168 165 160 167 179 156 155
  153 148 145 149 159 168 160 161 163 166]
 [183 182 179 174 167 162 159 158 151 143 155 176 164 128 117 131 151 158
  165 167 164 161 162 163 158 159 161 162]
 [163 163 165 168 172 175 177 177 185 181 171 157 147 150 164 176 157 163
  171 173 170 167 167 169 180 180 180 179]
 [184 181 180 182 188 190 189 186 188 190 193 192 183 171 163 161 164 164
  161 156 153 157 167 176 170 170 169 167]
 [117 110 104 102 103 101  95  88  93  80  72  73  66  50  41  43  46  51
   56  57  54  53  55  58  67  67  67  68]
 [156 152 151 158 169 176 175 171 188 196 187 167 168 182 176 152 162 161
  156 150 147 152 165 175 164 165 167 169]
 [173 173 172 171 169 168 167 167 184 175 165 161 165 172 176 17

/Users/admin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  """
/Users/admin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  
/Users/admin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:24: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.


In [147]:
scipy.misc.imsave('test_r.jpg', test_r)
scipy.misc.imsave('test_g.jpg', test_g)
scipy.misc.imsave('test_b.jpg', test_b)

/Users/admin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  """Entry point for launching an IPython kernel.
/Users/admin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  
/Users/admin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [148]:
print(test_r)
print(test_r.shape)

[[162 169 175 175 172 172 178 185 167 167 165 168 177 184 181 172 158 156
  152 145 142 148 160 170 171 170 170 169]
 [180 181 176 163 147 134 129 130 141 156 157 146 154 176 178 162 153 158
  164 164 162 160 162 165 166 167 168 169]
 [151 157 164 168 170 174 181 186 180 172 168 168 165 160 167 179 156 155
  153 148 145 149 159 168 160 161 163 166]
 [183 182 179 174 167 162 159 158 151 143 155 176 164 128 117 131 151 158
  165 167 164 161 162 163 158 159 161 162]
 [163 163 165 168 172 175 177 177 185 181 171 157 147 150 164 176 157 163
  171 173 170 167 167 169 180 180 180 179]
 [184 181 180 182 188 190 189 186 188 190 193 192 183 171 163 161 164 164
  161 156 153 157 167 176 170 170 169 167]
 [117 110 104 102 103 101  95  88  93  80  72  73  66  50  41  43  46  51
   56  57  54  53  55  58  67  67  67  68]
 [156 152 151 158 169 176 175 171 188 196 187 167 168 182 176 152 162 161
  156 150 147 152 165 175 164 165 167 169]
 [173 173 172 171 169 168 167 167 184 175 165 161 165 172 176 17

In [149]:
print(test_r.shape)

(28, 28)


In [150]:
print(type(test_r))

<class 'numpy.ndarray'>


In [151]:
test = test_r.reshape((1, 28, 28, 1))
print(test.shape)

(1, 28, 28, 1)
